angular = require('angular');
require('angular-mocks');
require('../../app/js/entry');
require('./handle_error_test');
require('./auth_test');
require('./fwhResource_test');
require('./signinController_test');
require('./signupController_test');
require('./trails_test');
require('./mapController_test');
